package com.vcredit.app.entities;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vcredit.app.entities.UrlCacheBean;

import com.vcredit.app.entities.UrlCacheBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig urlCacheBeanDaoConfig;

    private final UrlCacheBeanDao urlCacheBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        urlCacheBeanDaoConfig = daoConfigMap.get(UrlCacheBeanDao.class).clone();
        urlCacheBeanDaoConfig.initIdentityScope(type);

        urlCacheBeanDao = new UrlCacheBeanDao(urlCacheBeanDaoConfig, this);

        registerDao(UrlCacheBean.class, urlCacheBeanDao);
    }
    
    public void clear() {
        urlCacheBeanDaoConfig.clearIdentityScope();
    }

    public UrlCacheBeanDao getUrlCacheBeanDao() {
        return urlCacheBeanDao;
    }

}
