package com.vcredit.app.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "URL_CACHE_BEAN".
*/
public class UrlCacheBeanDao extends AbstractDao<UrlCacheBean, Long> {

    public static final String TABLENAME = "URL_CACHE_BEAN";

    /**
     * Properties of entity UrlCacheBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UrlMd5 = new Property(1, String.class, "urlMd5", false, "URL");
        public final static Property UrlResult = new Property(2, String.class, "urlResult", false, "URLRESULT");
    }


    public UrlCacheBeanDao(DaoConfig config) {
        super(config);
    }
    
    public UrlCacheBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"URL_CACHE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"URL\" TEXT," + // 1: urlMd5
                "\"URLRESULT\" TEXT);"); // 2: urlResult
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"URL_CACHE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UrlCacheBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String urlMd5 = entity.getUrlMd5();
        if (urlMd5 != null) {
            stmt.bindString(2, urlMd5);
        }
 
        String urlResult = entity.getUrlResult();
        if (urlResult != null) {
            stmt.bindString(3, urlResult);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UrlCacheBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String urlMd5 = entity.getUrlMd5();
        if (urlMd5 != null) {
            stmt.bindString(2, urlMd5);
        }
 
        String urlResult = entity.getUrlResult();
        if (urlResult != null) {
            stmt.bindString(3, urlResult);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UrlCacheBean readEntity(Cursor cursor, int offset) {
        UrlCacheBean entity = new UrlCacheBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // urlMd5
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // urlResult
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UrlCacheBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrlMd5(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUrlResult(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UrlCacheBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UrlCacheBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UrlCacheBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
