package com.vcredit.app.entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "URL_CACHE_BEAN".
*/
public class UrlCacheBeanDao extends AbstractDao<UrlCacheBean, Void> {

    public static final String TABLENAME = "URL_CACHE_BEAN";

    /**
     * Properties of entity UrlCacheBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UrlMd5 = new Property(0, String.class, "urlMd5", false, "URL_MD5");
        public final static Property UrlResult = new Property(1, String.class, "urlResult", false, "URL_RESULT");
    }


    public UrlCacheBeanDao(DaoConfig config) {
        super(config);
    }
    
    public UrlCacheBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"URL_CACHE_BEAN\" (" + //
                "\"URL_MD5\" TEXT," + // 0: urlMd5
                "\"URL_RESULT\" TEXT);"); // 1: urlResult
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"URL_CACHE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UrlCacheBean entity) {
        stmt.clearBindings();
 
        String urlMd5 = entity.getUrlMd5();
        if (urlMd5 != null) {
            stmt.bindString(1, urlMd5);
        }
 
        String urlResult = entity.getUrlResult();
        if (urlResult != null) {
            stmt.bindString(2, urlResult);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UrlCacheBean entity) {
        stmt.clearBindings();
 
        String urlMd5 = entity.getUrlMd5();
        if (urlMd5 != null) {
            stmt.bindString(1, urlMd5);
        }
 
        String urlResult = entity.getUrlResult();
        if (urlResult != null) {
            stmt.bindString(2, urlResult);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public UrlCacheBean readEntity(Cursor cursor, int offset) {
        UrlCacheBean entity = new UrlCacheBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // urlMd5
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // urlResult
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UrlCacheBean entity, int offset) {
        entity.setUrlMd5(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUrlResult(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(UrlCacheBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(UrlCacheBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(UrlCacheBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
